---
- name: Install packages
  become: True
  ignore_errors: True
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ zsh_packages }}"

- name: Set as default shell
  become: True
  user:
    name: "{{ item }}"
    shell: /bin/zsh
  with_items:
    - jan
    - root
- name: Create user/bin directory
  file:
    name: "{{ ansible_env.HOME }}/bin"
    state: directory

- name: Install zshrc
  template:
    src: zshrc.j2
    dest: "{{ ansible_env.HOME }}/.zshrc"
    mode: 0444

- name: Install root zshrc
  become: True
  template:
    src: zshrc.root.j2
    dest: /root/.zshrc
    mode: 0444
