---

postgresql_base_directory: /var/lib/postgres
postgresql_data_directory: "{{ postgresql_base_directory }}/data"
postgresql_config_directory: /etc/postgresql/11/main

postgresql_listen_addresses:
  - localhost

postgresql_port: 5432

postgresql_tls: False

postgresql_roles: []
# - name: name
#   superuser: False
#   createdb: False
#   createrole: False
#   inherit: False
#   login: False
#   replication: False
#   bypassrls: False
#   connection_limit: -1
#   password: "changeme"
#   valid_until: "yyyy-mm-dd"
#   in_role:
#     - parent1
#   role:
#     - child1
#   admin:
#     - child2

postgresql_databases: []
# - name: name
#   owner: role
#   encoding: UTF8
#   grants:            # supports table and database grants
#     - role: child1
#       privileges:    # omit for all privileges
#         - select
#       tables:        # omit for all tables
#         - table

postgresql_access_rights:
  - type: local
    database: all
    user: all
    address: ''
    method: 'peer'
    comment: 'UNIX users, "local" is for Unix domain socket connections only'
  - type: host
    database: all
    user: all
    address: '127.0.0.1/32'
    method: 'md5'
    comment: 'IPv4 local connections'
  - type: host
    database: all
    user: all
    address: '::1/128'
    method: 'md5'
    comment: 'IPv6 local connections'

