version: "3"

services:
  db:
    image: "postgres:11.7"
    logging:
      driver: none
    environment:
     - POSTGRES_PASSWORD=db
     - POSTGRES_USER=db
     - POSTGRES_DB=db
    expose:
     - 5432
    ports:
      - "5433:5432"
