version: "3"

services:

  mailserver:
    image: "mailhog/mailhog"
    hostname: mailserver
    logging:
      driver: none
    ports:
      - "8025:8025"
      - "1025:1025"

  db:
    build: "./docker/postgres"
    logging:
      driver: none
    environment:
     - POSTGRES_PASSWORD=db
     - POSTGRES_USER=db
     - POSTGRES_DB=db
    ports:
      - "5434:5432"

  selenium-hub:
    image: selenium/hub:3.141.59
    container_name: selenium-hub
    ports:
      - "4444:4444"
  firefox:
    image: selenium/node-firefox:3.141.59
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
