---
- name: Install package
  become: True
  package:
    name: nftables
    state: present

- name: Configure package
  become: True
  template:
    src: nftables.conf.j2
    dest: /etc/nftables.conf
    owner: root
    group: root
    mode: 0440
    backup: yes
    validate: nft -c -f %s
  notify: Restart service

- name: Start service
  become: True
  service:
    name: nftables
    state: started
    enabled: True
