---

- hosts: production
  roles:
    - role: zsh
      tags: zsh
    - role: vim
      tags: vim
    - role: hostname
      tags: hostname
    - role: postgresql
      tags: postgresql
    - role: nginx
      tags: nginx
