---
nftables:
  - name: firewall
    address_family: inet
    chains:
      - name: input
        type: filter
        hook: input
        rules:
          - ct state {established, related} accept

          # early drop of invalid connections
          - ct state invalid drop

          # allow from virtual devices
          - iifname lo accept

          # allow icmp but rate limit and log some of it
          - ip protocol icmp accept
          - ip6 nexthdr icmpv6 accept

          # DHCP
          - udp dport 68 accept
          - udp dport 67 accept
          # SSH
          - tcp dport 22 accept
          # HTTP
          - tcp dport 80 accept
          # HTTPS
          - tcp dport 443 accept

          # drop incomming protocols with rate limit
          - 'limit rate 1/second log prefix "Privileged access: " drop'
          - drop

      - name: forward
        type: filter
        hook: forward
        policy: drop

      - name: output
        type: filter
        hook: output
        policy: accept
