---
- name: Ensure .ssh folder exists for ssh default users
  become: True
  file:
    path: "/home/{{ item }}/.ssh/"
    state: directory
    owner: "{{ item }}"
    group: users
    mode: 0700
  with_items:
    - "{{ ssh_config_default_users }}"

- name: Create empty key string
  set_fact:
    ssh_config_authorized_key: ""

- name: Create concatenated key files for privileged user
  set_fact:
    ssh_config_authorized_key: "{{ [ssh_config_authorized_key, lookup('file', 'sshkeys/{{ item }}')] | join('\n') }}"
  with_items: "{{ ssh_config_privileged_users }}"

- name: Set up authorized keys for privileged user
  become: True
  authorized_key:
    user: "{{ ssh_config_privileged_user }}"
    state: present
    key: "{{ ssh_config_authorized_key }}"
    exclusive: yes

- name: Upload hardened ssh configs
  become: True
  template:
    src: "{{ item }}"
    dest: "/etc/ssh/{{ item }}"
    owner: root
    group: root
    mode: 0600
  with_items:
    - sshd_config
  notify: restart sshd
