---
elsa_backend_telegram_token: "{{ vault_elsa_backend_telegram_token }}"
elsa_backend_bot_name: elsahilfttestbot
elsa_backend_spring_profile: "testing"
elsa_backend_jwt_secret: "{{ vault_elsa_backend_jwt_secret }}"
