name: build

on:
  push:
    branches: [ testing ]

jobs:
  java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/cache@v1
        with:
          path: backend/build/jib-cache
          key: ${{ runner.os }}-jib
          restore-keys: |
            ${{ runner.os }}-jib
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Build image
        run: |
          cd backend
          ./gradlew jibDockerBuild

  public-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-public-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-public-node-
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Build public frontend
        run: |
          cd frontend/public
          npm install
          npm run build
  admin-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-admin-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-admin-node-
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Build admin frontend
        run: |
          cd frontend/admin
          npm install
          npm run build
